### ISSUE TITLE
docker無法啓動

### ISSUE THREAD

**Issue by ItJameaplay** [blackcatbot/blackcat#226]
### 目前行為

```js
Node.js v17.8.0
/home/catrunner/node_modules/discord.js/src/sharding/Shard.js:161
        reject(new Error('SHARDING_READY_DIED', this.id));
               ^

Error [SHARDING_READY_DIED]: Shard 0's process exited before its Client became ready.
    at Shard.onDeath (/home/catrunner/node_modules/discord.js/src/sharding/Shard.js:161:16)
    at Object.onceWrapper (node:events:642:26)
    at Shard.emit (node:events:527:28)
    at Shard._handleExit (/home/catrunner/node_modules/discord.js/src/sharding/Shard.js:399:10)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  [Symbol(code)]: 'SHARDING_READY_DIED'
}

Node.js v17.8.0
04/05 13:28:36 警告 找不到設定檔，正在從環境變數讀取
04/05 13:28:36 資訊 成功讀取設定
04/05 13:28:37 警告 找不到設定檔，正在從環境變數讀取
04/05 13:28:37 資訊 成功讀取設定
/home/catrunner/node_modules/bindings/bindings.js:126
  err = new Error(
        ^

Error: Could not locate the bindings file. Tried:
 → /home/catrunner/node_modules/node-libsamplerate/build/node-libsamplerate.node
 → /home/catrunner/node_modules/node-libsamplerate/build/Debug/node-libsamplerate.node
 → /home/catrunner/node_modules/node-libsamplerate/build/Release/node-libsamplerate.node
 → /home/catrunner/node_modules/node-libsamplerate/out/Debug/node-libsamplerate.node
 → /home/catrunner/node_modules/node-libsamplerate/Debug/node-libsamplerate.node
 → /home/catrunner/node_modules/node-libsamplerate/out/Release/node-libsamplerate.node
 → /home/catrunner/node_modules/node-libsamplerate/Release/node-libsamplerate.node
 → /home/catrunner/node_modules/node-libsamplerate/build/default/node-libsamplerate.node
 → /home/catrunner/node_modules/node-libsamplerate/compiled/17.8.0/linux/x64/node-libsamplerate.node
 → /home/catrunner/node_modules/node-libsamplerate/addon-build/release/install-root/node-libsamplerate.node
 → /home/catrunner/node_modules/node-libsamplerate/addon-build/debug/install-root/node-libsamplerate.node
 → /home/catrunner/node_modules/node-libsamplerate/addon-build/default/install-root/node-libsamplerate.node
 → /home/catrunner/node_modules/node-libsamplerate/lib/binding/node-v102-linux-x64/node-libsamplerate.node
    at bindings (/home/catrunner/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/home/catrunner/node_modules/node-libsamplerate/index.js:2:45)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24) {
  tries: [
    '/home/catrunner/node_modules/node-libsamplerate/build/node-libsamplerate.node',
    '/home/catrunner/node_modules/node-libsamplerate/build/Debug/node-libsamplerate.node',
    '/home/catrunner/node_modules/node-libsamplerate/build/Release/node-libsamplerate.node',
    '/home/catrunner/node_modules/node-libsamplerate/out/Debug/node-libsamplerate.node',
    '/home/catrunner/node_modules/node-libsamplerate/Debug/node-libsamplerate.node',
    '/home/catrunner/node_modules/node-libsamplerate/out/Release/node-libsamplerate.node',
    '/home/catrunner/node_modules/node-libsamplerate/Release/node-libsamplerate.node',
    '/home/catrunner/node_modules/node-libsamplerate/build/default/node-libsamplerate.node',
    '/home/catrunner/node_modules/node-libsamplerate/compiled/17.8.0/linux/x64/node-libsamplerate.node',
    '/home/catrunner/node_modules/node-libsamplerate/addon-build/release/install-root/node-libsamplerate.node',
    '/home/catrunner/node_modules/node-libsamplerate/addon-build/debug/install-root/node-libsamplerate.node',
    '/home/catrunner/node_modules/node-libsamplerate/addon-build/default/install-root/node-libsamplerate.node',
    '/home/catrunner/node_modules/node-libsamplerate/lib/binding/node-v102-linux-x64/node-libsamplerate.node'
  ]
}

```

### 預期行為

無錯誤啓動機器人

### 其他細節

使用系統: Ubuntu 21.10 x86_64/docker
node版本:17.8.0

**Comment by wolf-yuan-6115** [comment]
https://github.com/blackcatbot/blackcat/commit/eb5c5828ff404289bc3890918ff3640a973e01ff 應該有修復這個錯誤，請重新下載docker image並重試
