### ISSUE TITLE
Skip會出事

### ISSUE THREAD

**Issue by ItJameaplay** [blackcatbot/blackcat#236]
```js
file:///home/jamesliu0224/blackcat/src/audio/Player.js:286
      .setTitle(`⏭️ ┃ 跳過歌曲 **${this._audio.metadata.title}**`)
                                           ^

TypeError: Cannot read properties of undefined (reading 'metadata')
    at Player.skip (file:///home/jamesliu0224/blackcat/src/audio/Player.js:286:44)
    at file:///home/jamesliu0224/blackcat/src/commands/skip.js:10:14
    at requirePlayer (file:///home/jamesliu0224/blackcat/src/util/requirePlayer.js:36:3)
    at Object.run (file:///home/jamesliu0224/blackcat/src/commands/skip.js:9:5)
    at Object.run (file:///home/jamesliu0224/blackcat/src/events/commandInteraction.js:57:15)
    at Client.<anonymous> (file:///home/jamesliu0224/blackcat/src/instance.js:56:17)
    at Client.emit (node:events:527:28)
    at InteractionCreateAction.handle (/home/jamesliu0224/blackcat/node_modules/discord.js/src/client/actions/InteractionCreate.js:74:12)
    at Object.module.exports [as INTERACTION_CREATE] (/home/jamesliu0224/blackcat/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (/home/jamesliu0224/blackcat/node_modules/discord.js/src/client/websocket/WebSocketManager.js:351:31)

```
version 3.0.0
使用裝置/系統： Google Compute Engine/Debian GNU/Linux 11 (bullseye) x86_64

**Comment by wolf-yuan-6115** [comment]
Fixed
