### ISSUE TITLE
播放、待播清單問題

### ISSUE THREAD

**Issue by wibe01204** [blackcatbot/blackcat#308]
### 目前行為

1.播放清單按下一頁會顯示交互失敗
2.不確定讀取到哪首歌會出現以下錯誤，並解音樂會停止撥放
![image](https://user-images.githubusercontent.com/90883053/191882864-0a70bb57-9c89-4152-b612-2e9e3315f8c5.png)

![image](https://user-images.githubusercontent.com/90883053/191882446-f4406cd9-5ba6-445e-ac27-3306957e639e.png)
```09/23 02:43:00 錯誤 Cannot read properties of undefined (reading 'defaultIcon')
09/23 02:43:00 偵錯 TypeError: Cannot read properties of undefined (reading 'defaultIcon')
09/23 02:43:00 偵錯     at /home/yuru/blackcat/node_modules/play-dl/dist/index.js:2:2819
09/23 02:43:00 偵錯     at Array.find (<anonymous>)
09/23 02:43:00 偵錯     at video_basic_info (/home/yuru/blackcat/node_modules/play-dl/dist/index.js:2:2788)
09/23 02:43:00 偵錯     at runMicrotasks (<anonymous>)
09/23 02:43:00 偵錯     at processTicksAndRejections (node:internal/process/task_queues:96:5)
09/23 02:43:00 偵錯     at async Object.video_info (/home/yuru/blackcat/node_modules/play-dl/dist/index.js:3:1064)
09/23 02:43:00 偵錯     at async Player.playStream (file:///home/yuru/blackcat/src/audio/Player.js:492:19)
```

### 預期行為

1.清單應正常顯示至下一頁
2.應該可以顯示該歌曲讀取錯誤，會自行跳過該歌曲並繼續播放

**Comment by wolf-yuan-6115** [comment]
看起來是play-dl的問題，可能無法修復
